CC = gcc
OBJECTS		= 
LIBRARIES	=
PROGRAMS	= 00_sigsegv 01_sigusr1 02_sigalrm 03_sigchld 03_01_sigchld 01_pipe

.PHONY:         all clean

# Default target: build everything.
all:            $(OBJECTS) $(LIBRARIES) $(PROGRAMS)

# Clean up build products.
clean:
	rm -f *.o *.a $(PROGRAMS)
